sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t fsguoangeldocker/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true fsguoangeldocker/react-test npm test

after_success:
  - docker build -t fsguoangeldocker/multi-client ./client
  - docker build -t fsguoangeldocker/multi-nginx ./nginx
  - docker build -t fsguoangeldocker/multi-server ./server
  - docker build -t fsguoangeldocker/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push fsguoangeldocker/multi-client
  - docker push fsguoangeldocker/multi-nginx
  - docker push fsguoangeldocker/multi-server
  - docker push fsguoangeldocker/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'ap-southeast-2'
  app: 'multi-docker2'
  env: 'Multidocker2-env'
  bucket_name: 'elasticbeanstalk-ap-southeast-2-198792278499'
  bucket_path: 'docker-multi2'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY